name: Selenium Cucumber CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v4

      - name: Java Kurulumu
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Maven Bağımlılıklarını Yükle
        run: mvn clean install -DskipTests

      - name: Selenium Cucumber Testlerini Çalıştır
        run: mvn test || true  # Testler başarısız olsa bile workflow devam etsin

      - name: Allure Raporlarını Oluştur
        run: mvn allure:report || true  # Hata olsa bile çalışmaya devam et

      - name: Test Sonuçlarını ve Allure Raporlarını Kaydet
        if: always()
        uses: actions/upload-artifact@v4  # v3 yerine v4 kullanıldı
        with:
          name: allure-results
          path: target/allure-report
